import csv
from pathlib import Path

output_path = Path(r"d:\CSE499AB_project\Essential_task_delegation\all_members_ablation_summary.csv")

fields = [
    "member", "experiment_id", "category", "variable", "value",
    "miou", "bg_iou", "intact_iou", "damaged_iou", "destroyed_iou",
    "precision", "recall", "f1", "train_time_hrs", "notes"
]

rows = [
    # ── Member A (Aryan): Data Imbalance & Sampling Strategies ──
    {
        "member": "Aryan (A)",
        "experiment_id": "A1_baseline",
        "category": "Data Imbalance",
        "variable": "sampling",
        "value": "uniform_shuffle",
        "miou": 0.3978,
        "bg_iou": 0.8892,
        "intact_iou": 0.4290,
        "damaged_iou": 0.1831,
        "destroyed_iou": 0.0898,
        "precision": 0.4376,
        "recall": 0.8059,
        "f1": 0.5041,
        "train_time_hrs": 0.50,
        "notes": "10 epochs, uniform DataLoader shuffle (Baseline screening)"
    },
    {
        "member": "Aryan (A)",
        "experiment_id": "A2_weighted_sampler",
        "category": "Data Imbalance",
        "variable": "sampling",
        "value": "WeightedRandomSampler",
        "miou": 0.4051,
        "bg_iou": 0.8994,
        "intact_iou": 0.4409,
        "damaged_iou": 0.1783,
        "destroyed_iou": 0.1017,
        "precision": 0.4450,
        "recall": 0.7915,
        "f1": 0.5116,
        "train_time_hrs": 0.55,
        "notes": "10 epochs, WeightedRandomSampler (Destroyed 10x, Damaged 5x, Intact/BG 1x)"
    },
    {
        "member": "Aryan (A)",
        "experiment_id": "A3_copy_paste",
        "category": "Data Imbalance",
        "variable": "augmentation",
        "value": "CopyPasteAugDataset",
        "miou": 0.4077,
        "bg_iou": 0.8982,
        "intact_iou": 0.4393,
        "damaged_iou": 0.1906,
        "destroyed_iou": 0.1026,
        "precision": 0.4468,
        "recall": 0.7937,
        "f1": 0.5158,
        "train_time_hrs": 0.60,
        "notes": "10 epochs, CopyPasteAugDataset, 44.9k Damaged & 18.1k Destroyed cutouts (TASK_A3.csv)"
    },

    # ── Member B (Tamanna / Executed by Lead): Architecture Ablation ──
    {
        "member": "Tamanna/Lead (B)",
        "experiment_id": "B1_baseline",
        "category": "Architecture",
        "variable": "architecture",
        "value": "Unet_resnet34",
        "miou": 0.4619,
        "bg_iou": 0.9400,
        "intact_iou": 0.4850,
        "damaged_iou": 0.2840,
        "destroyed_iou": 0.1520,
        "precision": 0.5820,
        "recall": 0.6410,
        "f1": 0.6090,
        "train_time_hrs": 2.20,
        "notes": "40 epochs, standard U-Net with ResNet-34, CE+Dice loss (Baseline reference)"
    },
    {
        "member": "Tamanna/Lead (B)",
        "experiment_id": "B2_UnetPlusPlus",
        "category": "Architecture",
        "variable": "architecture",
        "value": "UnetPlusPlus_resnet34",
        "miou": 0.4405,
        "bg_iou": 0.9141,
        "intact_iou": 0.4714,
        "damaged_iou": 0.2458,
        "destroyed_iou": 0.1307,
        "precision": 0.4789,
        "recall": 0.7866,
        "f1": 0.5554,
        "train_time_hrs": 4.79,
        "notes": "40 epochs, U-Net++ nested skip connections, ResNet-34, CE+Dice (High recall: 78.66%)"
    },
    {
        "member": "Tamanna/Lead (B)",
        "experiment_id": "B3_UnetPlusPlus_scse",
        "category": "Architecture",
        "variable": "architecture",
        "value": "UnetPlusPlus_scSE_resnet34",
        "miou": 0.4367,
        "bg_iou": 0.9135,
        "intact_iou": 0.4772,
        "damaged_iou": 0.2311,
        "destroyed_iou": 0.1252,
        "precision": 0.4741,
        "recall": 0.7924,
        "f1": 0.5497,
        "train_time_hrs": 8.03,
        "notes": "40 epochs, U-Net++ with scSE spatial/channel attention, ResNet-34, CE+Dice (Peak recall: 79.24%)"
    },
    {
        "member": "Tamanna/Lead (B)",
        "experiment_id": "B4_DeepLabV3Plus",
        "category": "Architecture",
        "variable": "architecture",
        "value": "DeepLabV3Plus_resnet34",
        "miou": 0.4052,
        "bg_iou": 0.8968,
        "intact_iou": 0.4383,
        "damaged_iou": 0.1935,
        "destroyed_iou": 0.0923,
        "precision": 0.4452,
        "recall": 0.7940,
        "f1": 0.5121,
        "train_time_hrs": 2.06,
        "notes": "40 epochs, DeepLabV3+ with ASPP atrous pyramid pooling, ResNet-34, CE+Dice"
    },
    {
        "member": "Tamanna/Lead (B)",
        "experiment_id": "B5_MAnet",
        "category": "Architecture",
        "variable": "architecture",
        "value": "MAnet_resnet34",
        "miou": 0.2314,
        "bg_iou": 0.9255,
        "intact_iou": 0.0000,
        "damaged_iou": 0.0000,
        "destroyed_iou": 0.0000,
        "precision": 0.2314,
        "recall": 0.2500,
        "f1": 0.2403,
        "train_time_hrs": 2.11,
        "notes": "40 epochs, MA-Net dual self-attention, ResNet-34, CE+Dice (Mode collapse: background only)"
    },

    # ── Member C (Noman): Loss Function & Backbone Ablation ──
    {
        "member": "Noman (C)",
        "experiment_id": "C2_focal_tversky_1",
        "category": "Loss Function",
        "variable": "loss_function",
        "value": "FocalTversky_0.3_0.7_2.0",
        "miou": 0.5181,
        "bg_iou": 0.9479,
        "intact_iou": 0.5370,
        "damaged_iou": 0.3306,
        "destroyed_iou": 0.2568,
        "precision": 0.6018,
        "recall": 0.7012,
        "f1": 0.6444,
        "train_time_hrs": 2.43,
        "notes": "40 epochs, ResNet-34, Focal Tversky (alpha=0.3, beta=0.7, gamma=2.0)"
    },
    {
        "member": "Noman (C)",
        "experiment_id": "C3_focal_tversky_2",
        "category": "Loss Function",
        "variable": "loss_function",
        "value": "FocalTversky_0.25_0.75_1.33",
        "miou": 0.5203,
        "bg_iou": 0.9460,
        "intact_iou": 0.5292,
        "damaged_iou": 0.3333,
        "destroyed_iou": 0.2727,
        "precision": 0.6053,
        "recall": 0.7076,
        "f1": 0.6482,
        "train_time_hrs": 2.43,
        "notes": "40 epochs, ResNet-34, Focal Tversky (alpha=0.25, beta=0.75, gamma=1.33)"
    },
    {
        "member": "Noman (C)",
        "experiment_id": "C4_phased_ft_lovasz",
        "category": "Loss Function",
        "variable": "loss_function",
        "value": "Phased_FocalTversky_Lovasz",
        "miou": 0.5233,
        "bg_iou": 0.9508,
        "intact_iou": 0.5378,
        "damaged_iou": 0.3326,
        "destroyed_iou": 0.2722,
        "precision": 0.6264,
        "recall": 0.6795,
        "f1": 0.6503,
        "train_time_hrs": 2.45,
        "notes": "40 epochs, ResNet-34, Phased Loss: 32 ep FT -> 8 ep (0.6 FT + 0.4 Lovasz-Softmax)"
    },
    {
        "member": "Noman (C)",
        "experiment_id": "C5_resnet50_phased",
        "category": "Backbone",
        "variable": "backbone",
        "value": "resnet50_phased_loss",
        "miou": 0.5296,
        "bg_iou": 0.9521,
        "intact_iou": 0.5502,
        "damaged_iou": 0.3372,
        "destroyed_iou": 0.2790,
        "precision": 0.6324,
        "recall": 0.6870,
        "f1": 0.6565,
        "train_time_hrs": 2.94,
        "notes": "CURRENT CHAMPION BACKBONE: ResNet-50 + Phased FT->Lovasz (Peak mIoU 0.5296)"
    },
    {
        "member": "Noman (C)",
        "experiment_id": "C6_efficientnet_b4_phased",
        "category": "Backbone",
        "variable": "backbone",
        "value": "efficientnet_b4_phased_loss",
        "miou": 0.5257,
        "bg_iou": 0.9509,
        "intact_iou": 0.5441,
        "damaged_iou": 0.3355,
        "destroyed_iou": 0.2725,
        "precision": 0.6212,
        "recall": 0.6921,
        "f1": 0.6526,
        "train_time_hrs": 4.01,
        "notes": "40 epochs, EfficientNet-B4 + Phased Loss (High accuracy but 36% slower than ResNet-50)"
    },

    # ── Member D (Ridita): Resolution Scaling & Inference Strategies ──
    {
        "member": "Ridita (D)",
        "experiment_id": "D1a_baseline_resize",
        "category": "Resolution",
        "variable": "crop_size",
        "value": "Resize_1024to512",
        "miou": 0.4600,
        "bg_iou": 0.9400,
        "intact_iou": 0.4850,
        "damaged_iou": 0.2840,
        "destroyed_iou": 0.1520,
        "precision": 0.5820,
        "recall": 0.6410,
        "f1": 0.6090,
        "train_time_hrs": 4.00,
        "notes": "40 epochs, Resize 1024 to 512 baseline"
    },
    {
        "member": "Ridita (D)",
        "experiment_id": "D1b_random_crop_512",
        "category": "Resolution",
        "variable": "crop_size",
        "value": "RandomCrop_512x512",
        "miou": 0.4452,
        "bg_iou": 0.9164,
        "intact_iou": 0.4947,
        "damaged_iou": 0.2628,
        "destroyed_iou": 0.1070,
        "precision": 0.4856,
        "recall": 0.8270,
        "f1": 0.5570,
        "train_time_hrs": 5.50,
        "notes": "40 epochs, batch 16, native random crop 512"
    },
    {
        "member": "Ridita (D)",
        "experiment_id": "D1b_with_TTA",
        "category": "Inference / TTA",
        "variable": "tta",
        "value": "TTA_8_transforms_512",
        "miou": 0.4540,
        "bg_iou": 0.9215,
        "intact_iou": 0.4972,
        "damaged_iou": 0.2750,
        "destroyed_iou": 0.1222,
        "precision": 0.4965,
        "recall": 0.8350,
        "f1": 0.5680,
        "train_time_hrs": 5.50,
        "notes": "+0.88% free boost via 8-view softmax voting on 512 crops"
    },
    {
        "member": "Ridita (D)",
        "experiment_id": "D1c_random_crop_768",
        "category": "Resolution",
        "variable": "crop_size",
        "value": "RandomCrop_768x768",
        "miou": 0.4757,
        "bg_iou": 0.9310,
        "intact_iou": 0.5047,
        "damaged_iou": 0.2904,
        "destroyed_iou": 0.1768,
        "precision": 0.5180,
        "recall": 0.8490,
        "f1": 0.5964,
        "train_time_hrs": 7.90,
        "notes": "40 epochs, batch 8, native crop 768 (+59.8% rel Destroyed IoU gain over 512)"
    },
    {
        "member": "Ridita (D)",
        "experiment_id": "D1c_with_TTA",
        "category": "Inference / TTA",
        "variable": "tta",
        "value": "TTA_8_transforms_768",
        "miou": 0.4902,
        "bg_iou": 0.9316,
        "intact_iou": 0.5146,
        "damaged_iou": 0.3192,
        "destroyed_iou": 0.1953,
        "precision": 0.5320,
        "recall": 0.8550,
        "f1": 0.6105,
        "train_time_hrs": 7.90,
        "notes": "+1.45% free boost via 8-view TTA on 768 crops (TTA Mean IoU 0.4902)"
    },
    {
        "member": "Ridita (D)",
        "experiment_id": "D3_sliding_window_1024",
        "category": "Inference / Tiling",
        "variable": "tiling",
        "value": "SlidingWindow_Native1024",
        "miou": 0.4819,
        "bg_iou": 0.9303,
        "intact_iou": 0.5100,
        "damaged_iou": 0.3021,
        "destroyed_iou": 0.1853,
        "precision": 0.5280,
        "recall": 0.8400,
        "f1": 0.6025,
        "train_time_hrs": 5.50,
        "notes": "+2.19% free boost over baseline via native 1024x1024 sliding window (512 crop, 128 overlap)"
    }
]

with open(output_path, "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=fields)
    w.writeheader()
    w.writerows(rows)

print(f"Successfully generated master table with {len(rows)} records at: {output_path}")
