import os
import ollama 
import argparse
import json

def parsing_arguments():
    parser = argparse.ArgumentParser(description="VLM-as-a-Jury: Automated evaluation of disaster assessments.")

    parser.add_argument(
        "--jury", "-j",
        type=str,
        default="gemma3:27b",
        help="The name of the VLM acting as the judge (Default: gemma3:27b)"
    )

    parser.add_argument(
        "--candidate", "-c",
        type=str,
        default="gemma3:27b",
        help="The VLM model output being evaluated"
    )

    return parser.parse_args()

def jury_loop(jury_model, candidate_model):
    """
    Evaluates candidate model descriptions against ground-truth images using 
    a 'Jury' VLM to provide a quantitative score and qualitative reasoning.
    """
    
    # --- Generic Path Configuration ---
    # Location of the pre/post disaster image folders
    BASE_IMAGE_ROOT = "./data/images/"
    
    # Location of the .txt assessment files generated by the candidate model
    safe_candidate_model = candidate_model.replace(':', '_')
    CANDIDATE_ROOT = f"./results/vlm_assessments/{safe_candidate_model}/"

    # Organized output structure: results/jury_model/candidate_model/
    safe_jury_model = jury_model.replace(':', '_')
    OUTPUT_ROOT = os.path.join("./results/jury_evaluations", safe_jury_model, safe_candidate_model)
    os.makedirs(OUTPUT_ROOT, exist_ok=True)

    print(f"Jury Model: {jury_model} | Evaluating Candidate: {candidate_model}")
    print(f"Results Directory: {OUTPUT_ROOT}")
    
    # Gather image subfolders (assumes folders are named by ID)
    try:
        image_folders = sorted([f for f in os.listdir(BASE_IMAGE_ROOT) if os.path.isdir(os.path.join(BASE_IMAGE_ROOT, f))])
    except FileNotFoundError:
        print(f"Error: IMAGE_ROOT directory not found at {BASE_IMAGE_ROOT}")
        return

    for folder_id in image_folders: 
        assessment_file = os.path.join(CANDIDATE_ROOT, f"{folder_id}_assessment.txt")

        if not os.path.exists(assessment_file):
            print(f"Skipping ID {folder_id}: Candidate assessment file not found.")
            continue

        with open(assessment_file, 'r', encoding='utf-8') as f:
            candidate_text = f.read()

        # Define image paths (Generic naming convention)
        folder_path = os.path.join(BASE_IMAGE_ROOT, folder_id)
        pre_path = os.path.join(folder_path, f"{folder_id}_pre_disaster.png")
        post_path = os.path.join(folder_path, f"{folder_id}_post_disaster.png")

        # Validation to prevent model hallucinations based on missing data
        if not os.path.exists(pre_path) or not os.path.exists(post_path):
            print(f"WARNING: Image pairs missing for ID {folder_id}. Skipping.")
            continue
        
        print(f"\n{'='*20} Evaluating ID: {folder_id} {'='*20}")

        full_response_text = ""
        try:
            # VLM Jury Analysis via Ollama API
            model_stream = ollama.chat(
                model=jury_model,
                messages=[{
                    'role': 'user',
                    'content': f"""You are a Senior Structural Engineer and Disaster Response Evaluator acting as an impartial member of a jury. 

Your task is to evaluate the accuracy of an AI Model's damage assessment report (Candidate) by comparing it against your own analysis of the provided images.

### DEFINITION OF DAMAGE SCALE (1-4)
- 1: No/Slight Damage - Least concern
- 2: Moderate Damage - Moderate concern
- 3: Major Damage - Severe concern
- 4: Destroyed/Collapsed - Most concern

### EVALUATION RULES
1. **Do Not Penalize Logical Inference:** If the AI describes specific damage (e.g., "roof removed") that logically supports your own analysis (e.g., "significant damage"), mark this as CORRECT.
2. **Penalize Contradictions:** If the AI claims damage exists where you find "no damage," this is a HALLUCINATION. Penalize heavily.
3. **Penalize Safety Risks:** Underestimating damage (e.g., classifying a destroyed building as "minor damage") is a critical safety failure. Score this below 50.
4. **Check Classification:** Ensure the numerical classification (1-4) aligns with the severity described in the analysis.
5. **Do Not Penalize Verbosity:** If the AI is verbose and makes logical predictions based on the images, do not apply a punishment.

### SCORING RUBRIC (0-100)
- **90-100 (Excellent):** Perfectly captures core truth. Plausible details. Correct safety classification.
- **75-89 (Good):** Factually correct about main damage; minor inconsistencies in tone or detail.
- **50-74 (Weak):** Misses key structures or provides vague/unhelpful descriptions.
- **0-49 (Critical Failure):** Hallucinations, missed destruction, or dangerous under-estimation of risk.

### OUTPUT FORMAT
You must output your evaluation in valid JSON format only. Do not provide preamble or markdown formatting. 

{{
    "score": <integer_0-100>,
    "classification_accuracy": <"correct", "underestimated", or "overestimated">,
    "reasoning": "<Concise explanation of score, specifically referencing the comparison.>"
}}

# DATA FOR EVALUATION
CANDIDATE ASSESSMENT:
{candidate_text}""",
                'images': [pre_path, post_path]
                }],
                options={'num_ctx': 16384},
                stream=True,
            )

            # Stream response to terminal for real-time monitoring
            for chunk in model_stream:
                content = chunk['message']['content']
                print(content, end='', flush=True)
                full_response_text += content

            # Clean and parse JSON response
            clean_json = full_response_text.strip()
            if clean_json.startswith("```json"):
                clean_json = clean_json.split("```json")[1].split("```")[0].strip()
            elif clean_json.startswith("```"):
                clean_json = clean_json.split("```")[1].split("```")[0].strip()

            try:
                data = json.loads(clean_json)
                
                # Metadata Injection
                data["jury_model"] = jury_model
                data["candidate_model"] = candidate_model
                data["folder_id"] = folder_id

                # Save structured JSON
                output_file = os.path.join(OUTPUT_ROOT, f"{folder_id}_jury_result.json")
                with open(output_file, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=4)
                
                print(f"\n\n[SUCCESS] Result saved to: {output_file}")

            except json.JSONDecodeError:
                # Fallback: Save as raw text if JSON parsing fails
                output_file = os.path.join(OUTPUT_ROOT, f"{folder_id}_jury_result.txt")
                with open(output_file, "w", encoding="utf-8") as f:
                    f.write(full_response_text)
                print(f"\n\n[WARNING] Invalid JSON format. Saved as raw text.")

        except Exception as e:
            print(f"\n[ERROR] Failed to process ID {folder_id}: {e}")

if __name__ == "__main__":
    args = parsing_arguments()
    jury_loop(jury_model=args.jury, candidate_model=args.candidate)
    print("\nEvaluation complete: All candidate reports ranked.\n")
